# Site settings
title: 千柱之城
email: vilofee@126.com
description: > # this means to ignore newlines until "baseurl:"
  最近正在研究zookeeper
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vilofee.github.io" # the base hostname & protocol for your site
twitter_username: zhsh411
github_username:  vilofee

# Build settings
markdown: kramdown


